os: linux
language: node_js
node_js:
  - "node"
  - "4"
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: eba755efcb1fc3628cd30fc5a2c33a51d15c60a5e471bddda05e41927e89cdf5
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  # https://docs.travis-ci.com/user/encryption-keys/#Usage
  provider: npm
  api_key: "f7629d8e-3d57-49e1-a818-c7dc624602cc",
  on:
    tags: true
    branch: master
